Section21/first_project/first_app/urls.py
from django.conf.urls import url
from django.urls import path
from first_app import views

# Template tagging
app_name = 'first_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('index/', views.index, name='index'),
    path('users/', views.users, name='users'),
    path('formpage/', views.form_name_view, name='form_page'),
    path('other/', views.other, name='other'),
    path('relative_url_templates/', views.relative_url_templates, name='relative_url_templates'),
    path('registration/', views.registration, name='registration'),
    path('login/', views.user_login, name='user_login'),
]

Section21/first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from first_app import views


urlpatterns = [
    path('', views.index, name='index'),
    path('first_app/',include('first_app.urls')),
    path('admin/', admin.site.urls),
    path('logout/', views.user_logout, name='user_logout'),
]

Section21/first_project/first_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

from mylogger import logging

class Topic(models.Model):
    """docstring for Topic."""
    logging.warning('test test')
    top_name = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.top_name

class Webpage(models.Model):
    """docstring for Webpage."""
    logging.warning('test test')
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=264, unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    """docstring for AccessRecord."""
    logging.warning('test test')
    name = models.ForeignKey(Webpage, on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

class MyUser(models.Model):
    """docstring for MyUser."""
    logging.warning('test test')
    first_name = models.CharField(max_length=264)
    last_name = models.CharField(max_length=264)
    email = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.first_name + self.last_name

# Create your models here.
class UserProfileInfo(models.Model):

    # Create relationship (don't inherit from User!)
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    # Add any additional attributes you want
    portfolio_site = models.URLField(blank=True)
    # pip install pillow to use this!
    # Optional: pip install pillow --global-option=”build_ext” --global-option=”--disable-jpeg”
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.user.username

Section21/first_project/first_app/forms.py
from django import forms
from django.core import validators
from first_app.models import UserProfileInfo, MyUser
from django.contrib.auth.models import User

def check_for_z(value):
    if value[0].lower() != 'z':
        raise forms.ValidationError("Name Needs to start with Z")

class FormName(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    verify_email = forms.EmailField(label='Enter your email again')
    text = forms.CharField(widget=forms.Textarea)
    days = forms.ChoiceField(choices=[(x, x) for x in range(1, 32)])
    names = forms.ModelChoiceField(queryset=MyUser.objects.order_by('first_name'))
    botcatcher = forms.CharField(required=False,
                                widget=forms.HiddenInput,
                                validators=[validators.MaxLengthValidator(0)])

    def clean(self):
        all_clean = super().clean()
        email = all_clean['email']
        vmail = all_clean['verify_email']
        if email != vmail:
            raise forms.ValidationError("Make sure emails match")


class NewUserForm(forms.ModelForm):
    class Meta():
        model = MyUser
        fields = ('first_name', 'last_name','email')

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

Section21/first_project/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from first_app.models import Topic, Webpage, AccessRecord, MyUser, UserProfileInfo
from first_app.forms import NewUserForm,UserForm,UserProfileInfoForm,FormName

from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from mylogger import logging

logging.debug('Test log')

def index(request):
    logging.debug(request)
    con_dict = {'text':'hello world','number':100}
    logging.info('testing')
    return render(request,'first_app/index.html',context=con_dict)

def other(request):
    logging.debug(request)
    webpages_list = AccessRecord.objects.order_by('date')
    date_dict = {"access_records":webpages_list}
    return render(request,'first_app/other.html',context=date_dict)

def relative_url_templates(request):
    logging.debug(request)
    return render(request,'first_app/relative_url_templates.html')


#def users(request):
#    user_list = MyUser.objects.order_by('first_name')
#    user_dict = {"users_records":user_list}
#    return render(request,'first_app/users.html',context=user_dict)

def users(request):
    logging.debug(request)
    user_list = MyUser.objects.order_by('first_name')
    user_dict = {"users_records":user_list}
    form = NewUserForm()
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print('ERROR FORM INVALID')
    return render(request,'first_app/users.html',{'form':form, "users_records":user_list})

def form_name_view(request):
    logging.debug(request)
    form = FormName()
    if request.method == 'POST':
        form = FormName(request.POST)
        if form.is_valid():
            print("Validation")
            print("Name : " +form.cleaned_data['name'])
            print("Email : " +form.cleaned_data['email'])
            print("Text : " +form.cleaned_data['text'])
    return render(request,'first_app/form_page.html',{'form':form})

def registration(request):
    logging.debug(request)
    registered = False
    if request.method == 'POST':
        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():
            # Save User Form to Database
            user = user_form.save()
            # Hash the password
            user.set_password(user.password)
            # Update with Hashed password
            user.save()
            # Now we deal with the extra info!
            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)
            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user
            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']
            # Now save model
            profile.save()
            # Registration Successful!
            registered = True
        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)
    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'first_app/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

@login_required
def user_logout(request):
    logging.debug(request)
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def user_login(request):
    logging.debug(request)
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account not active")
        else:
            print("Someone tried to login and failed")
            print("Username: {} and Password: {}".format(username,password))
            return HttpResponse("INVALID Login details supplied")
    else:
        return render(request, 'first_app/login.html',{})

Section21/first_project/templates/first_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load my_templates %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Section21</title>
    <title></title>
  </head>
  <body>
    <h1>Hello World</h1>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="{% url 'first_app:index' %}">BRAND</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarToggler">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'first_app:other' %}">Other</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'first_app:relative_url_templates' %}">Relative_url_templates</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'first_app:users' %}">Users</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'first_app:registration' %}">Registration</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'first_app:form_page' %}">Forms</a>
            </li>

            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'user_logout' %}">Logout</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'first_app:user_login' %}">Login</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      <!-- Extending the base.html -->
      {% endblock %}
    </div>
  </body>
</html>

Section21/first_project/templates/first_app/form_page.html
{% extends "first_app/base.html" %}
  {% block body_block %}
  <div class="container">
    <h1>Fill out form</h1>
    <form method="post">
      {{form.as_p}}
      {% csrf_token %}
      <input type="submit" class="btn btn-primary" value="submit">
    </form>
  </div>
{% endblock %}

Section21/first_project/templates/first_app/index.html
{% extends "first_app/base.html" %}
{% load my_templates %}
{% load staticfiles %}
  {% block body_block %}
    <div class="container">
      <h1>Section 21</h1>
      <div class="container">
        <div class="jumbotron">
          <h2>Welcome to the Django Project</h2>
        </div>
        
        {% if user.is_authenticated %}
          {{ text|myFilter:'world'}}
          {{ number|add:"99" }}
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        {% endif %}


      </div>

    </div>
  {% endblock %}

Section21/first_project/templates/first_app/login.html
{% extends "first_app/base.html" %}
{% load my_templates %}
  {% block body_block %}
    <h1>Section 21</h1>
      <div class="jumbotron">
        <h2>Login</h2>
        <form class="" action="{% url 'first_app:user_login' %}" method="post">
          {% csrf_token %}
          <label for="username">Username : </label>
          <input type="text" name="username" placeholder="Enter Username">
          <label for="password">Password : </label>
          <input type="password" name="password">
          <input type="submit" value="Login">
        </form>
      </div>
      {{ text|myFilter:'world'}}
      {{ number|add:"99" }}
    </div>
  {% endblock %}

Section21/first_project/templates/first_app/other.html
{% extends "first_app/base.html" %}
  {% block body_block %}
  <h1>Welcome to Other.html</h1>
  <h2>Template Inheritance</h2>
  <h2>Here are your access records</h2>
  <div class="django">
    {% if access_records %}
    <table>
      <thead>
        <th>Site name</th>
        <th>Date Accessed</th>
      </thead>

      {% for acc in access_records %}
      <tr>
        <td>{{ acc.name }}</td>
        <td>{{ acc.date }}</td>
      </tr>
      {% endfor %}
    </table>

    {% else %}
    <p>No Access Records found</p>
    {% endif %}
  </div>
  {% endblock %}

Section21/first_project/templates/first_app/registration.html
{% extends "first_app/base.html" %}
{% load my_templates %}
  {% block body_block %}
    <div class="jumbotron">
      <h1>Welcome to registration.html</h1>
      <h2>Template Inheritance</h2>

      {% if registered %}
        <h3>Thank You for Registering</h3>
      {% else %}
        <h3>Register Here</h3>
        <h5>Fill out the form:</h5>

        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" value="Register">
        </form>
        {% endif %}
    </div>
  {% endblock %}

Section21/first_project/templates/first_app/relative_url_templates.html
{% extends "first_app/base.html" %}
  {% block body_block %}
  <h1>Welcome to relative_url_templates.html</h1>
  <h2>Template Inheritance</h2>
  {% endblock %}

Section21/first_project/templates/first_app/users.html
{% extends "first_app/base.html" %}
  {% block body_block %}
    <h1>Welcome to users.html</h1>
    <h2>Template Inheritance</h2>
    <div class="container">
      <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Submit">
      </form>

      <h2>Here are your user records</h2>
      <div class="django">
        {% if users_records %}
        <ol>
          {% for user in users_records %}
          <li>User Info</li>
            <ul>
              <li>First Name: {{ user.first_name }}</li>
              <li>Last Name: {{ user.last_name }}</li>
              <li>Email: {{ user.email }}</li>
            </ul>
            {% endfor %}
        </ol>

        {% else %}
        <p>No User Records found</p>
        {% endif %}
      </div>
    </div>
  {% endblock %}