01Project/theproject/theapp/urls.py
from django.conf.urls import url
from django.urls import path
from theapp import views

# Template tagging
app_name = 'theapp'

urlpatterns = [
    path('', views.home, name='home'),
    path('index/', views.index, name='index'),
]

01Project/theproject/theproject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from theapp import views

from .views import welcome

urlpatterns = [
    path('', views.home, name='home'),
    path('theapp/',include('theapp.urls')),
    path('admin/', admin.site.urls),
    path('welcome/', welcome, name='welcome'),
]

01Project/theproject/theapp/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Account(models.Model):
    user_id = models.AutoField(primary_key=True)
    username = models.CharField(unique=True, max_length=50)
    password = models.CharField(max_length=50)
    email = models.CharField(unique=True, max_length=355)
    created_on = models.DateTimeField()
    last_login = models.DateTimeField(blank=True, null=True)
    build_status = models.CharField(max_length=50, blank=True, null=True)
    infra_status = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'account'


class AccountRole(models.Model):
    user = models.ForeignKey(Account, models.DO_NOTHING, primary_key=True)
    role = models.ForeignKey('Role', models.DO_NOTHING)
    grant_date = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'account_role'
        unique_together = (('user', 'role'),)


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.BooleanField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.BooleanField()
    is_active = models.BooleanField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.SmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Role(models.Model):
    role_id = models.AutoField(primary_key=True)
    role_name = models.CharField(unique=True, max_length=255)

    class Meta:
        managed = False
        db_table = 'role'

01Project/theproject/theapp/views.py
from django.shortcuts import render, redirect
from theapp.models import Account,Role,AccountRole
import json
from django.http import HttpResponse, HttpResponseRedirect
import sys

# Create your views here.
def index(request):
    if request.method == "POST":
        payload = request.POST.dict();

        entry = ""
        try:
            entry = Account.objects.get(username=payload['username'])
        except:
            print("Oops!",sys.exc_info()[0],"occured.")

        if entry:
            created = Account.objects.filter(username=payload['username']).update(password=payload['password'],build_status="null",infra_status="null")
        else:
            created = Account.objects.create(username=payload['username'],
                                            email=payload['username'],
                                            password=payload['password'],
                                            created_on='1997-03-28 00:00:00',
                                            last_login='1997-03-28 00:00:00')

        return redirect('theapp:index')
    elif request.method == "GET":
        users_list = Account.objects.order_by('user_id')
        role_list = Role.objects.order_by('role_id')
        accRole_list = AccountRole.objects.order_by('user_id')
        dict_dict = {"user_records":users_list, "role_records":role_list, "accrole_records":accRole_list}
        return render(request,'theapp/index.html',context=dict_dict)

def home(request):
    return render(request, 'theapp/home.html', context={})

01Project/theproject/theproject/views.py
from django.http import HttpResponse


def welcome(request):
    return HttpResponse("Hello World")

01Project/theproject/templates/theapp/base.html
<!DOCTYPE html>
{% include "theapp/header.html" %}
{% load staticfiles %}
{% load my_templates %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block head_block %}
    <!-- Extending the base.html -->
    {% endblock %}
    <title>TheProject</title>
    <title></title>
  </head>
  <body>
    {% block header_block %}
    <!-- from the header.html -->
    {% endblock %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="{% url 'theapp:home' %}">BRAND</a>
        <a class="navbar-brand" href="{% url 'theapp:index' %}">index</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarToggler">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      <!-- Extending the base.html -->
      {% endblock %}
    </div>
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> -->
  </body>
</html>

01Project/theproject/templates/theapp/header.html
{% block header_block %}
<h1>FROM the Header</h1>
{% endblock %}

01Project/theproject/templates/theapp/home.html
{% extends "theapp/base.html" %}
{% load staticfiles %}
{% load my_templates %}
  {% block head_block %}
    <link rel="stylesheet" href="{% static 'theapp/style.css' %}" type="text/css">
  {% endblock %}
  {% block body_block %}
  <script src="http://code.jquery.com/jquery-latest.js"></script>
  <div class="jumbotron">
    <h2>Login</h2>
    <form class="" action="{% url 'theapp:index' %}" method="post">
      {% csrf_token %}
      <label for="username">Username : </label>
      <input type="text" name="username" placeholder="Enter Username">
      <label for="password">Password : </label>
      <input type="password" name="password">
      <input type="submit" value="Login">
    </form>
  </div>

      <script type="text/javascript" src="{% static 'js/home.js' %}"></script>
  {% endblock %}

01Project/theproject/templates/theapp/index.html
{% extends "theapp/base.html" %}
{% load staticfiles %}
{% load my_templates %}
  {% block head_block %}
    <link rel="stylesheet" href="{% static 'theapp/style.css' %}" type="text/css">
  {% endblock %}
  {% block body_block %}
  <script src="http://code.jquery.com/jquery-latest.js"></script>

    <div class="jumbotron">
      <h2>Welcome to the The Project</h2>
    </div>
    <a href="{% url 'theapp:index'%}">Refresh</a>
    <div id="content">
      {% csrf_token %}
      {% if user_records %}
      <table class="table table-striped">
        <thead class="thead-dark">
          <th>User ID</th>
          <th>UserName</th>
          <th>Password</th>
          <th>Build Status</th>
          <th>Infra Status</th>
        </thead>
        {% for acc in user_records %}
        <tr>
          <td>{{ acc.user_id }}</td>
          <td>{{ acc.username }}</td>
          <td>{{ acc.password }}</td>
          <!-- <td>{{ acc.status }}</td> -->
          {% if acc.build_status == 'FAILED' %}
            <td><img id="hover_blink" class="failed" src="{% static 'images/redball.jpg' %}" alt="My image" style="height: 85px; width: 85px"></td>
          {% elif acc.build_status == 'SUCCESS' %}
            <td><img id="hover_blink" class="success" src="{% static 'images/greenball.jpg' %}" alt="My image" style="height: 85px; width: 85px"></td>
          {% else %}
            <td><img class="flashit" id="hover_blink" src="{% static 'images/redball.jpg' %}" alt="My image" style="height: 85px; width: 85px"></td>
          {% endif %}
          {% if acc.infra_status == 'FAILED' %}
            <td><img id="hover_blink" src="{% static 'images/redball.jpg' %}" alt="My image" style="height: 85px; width: 85px"></td>
          {% elif acc.infra_status == 'SUCCESS' %}
            <td><img id="hover_blink" src="{% static 'images/greenball.jpg' %}" alt="My image" style="height: 85px; width: 85px"></td>
          {% else %}
            <td><img class="flashit" id="hover_blink" src="{% static 'images/redball.jpg' %}" alt="My image" style="height: 85px; width: 85px"></td>
          {% endif %}
        </tr>
        {% endfor %}
      </table>
      {% else %}
      <p>No Access Records found</p>
      {% endif %}
    </div>

    <!-- <script type="text/javascript" src="{% static 'js/index.js' %}"></script> -->
  {% endblock %}