adv_blog/advcbv/advcbv/urls.py
from django.contrib import admin
from django.urls import path
from basic_app import views, urls
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('index/', views.IndexView.as_view(), name='index'),
    path('basic_app/', include('basic_app.urls'),name="basic_app"),
]

adv_blog/advcbv/basic_app/urls.py
from django.conf.urls import url
from django.urls import path
from basic_app import views
from django.conf.urls import include

app_name = 'basic_app'

urlpatterns = [
    path('',views.SchoolListView.as_view(),name="list"),
    path('detail/<int:pk>/',views.SchoolDetailView.as_view(), name="detail"),
    path('create/',views.SchoolCreateView.as_view(),name="create"),
    path('update/<int:pk>/',views.SchoolUpdateView.as_view(), name="update"),
    path('delete/<int:pk>/',views.SchoolDeleteView.as_view(), name="delete"),
]

adv_blog/advcbv/basic_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class School(models.Model):
    name = models.CharField(max_length=256)
    principle = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("basic_app:detail",kwargs={'pk':self.pk})

class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

adv_blog/advcbv/basic_app/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, DeleteView, UpdateView
from django.http import HttpResponse
from . import models
from django.urls import reverse_lazy

# Create your views here.
class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['inject_me'] = 'basic injection'
        return context


class SchoolListView(ListView):
    context_object_name = 'school' # List View will return schools_list by default
    model = models.School


class SchoolDetailView(DetailView):
    context_object_name = 'school_detail' # Detail View will return schools by default
    model = models.School
    template_name = 'basic_app/school_detail.html'


class SchoolCreateView(CreateView):
    fields = ('name','principle','location')
    model = models.School


class SchoolUpdateView(UpdateView):
    fields = ('name','principle')
    model = models.School


class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("basic_app:list")

adv_blog/advcbv/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Base</title>
  </head>
  <body>

    <nav class="navbar navbar-static-top navbar-expand-lg navbar-light bg-light">
      <ul class="nav navbar-nav">
        <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>
        <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
        <li><a href="#"></a></li>
      </ul>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

adv_blog/advcbv/basic_app/templates/basic_app/school_confirm_delete.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
  <h1>Delete {{ school.name }}?</h1>
  <form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="delete">
    <a href="{% url 'basic_app:detail' pk=school.pk %}">Cancle</a>
  </form>
{% endblock %}

adv_blog/advcbv/basic_app/templates/basic_app/school_detail.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
<div class="jumbotron">
  <h1>Welcome to the School Detail Page</h1>
  <h2>School Details:</h2>
  <p>Name: {{ school_detail.name }}</p>
  <p>Principal: {{ school_detail.principle }}</p>
  <p>Location: {{ school_detail.location }}</p>
  <h3>Students:</h3>
  {% for student in school_detail.students.all %}
    <p>{{ student.name }} who is {{ student.age }} years old</p>
  {% endfor %}
</div>
<div class="container">
  <p>
    <a class="btn btn-warning" href="{% url 'basic_app:update' pk=school_detail.pk %}">Update</a>
    <a class="btn btn-danger" href="{% url 'basic_app:delete' pk=school_detail.pk %}">Delete</a>
  </p>
</div>
{% endblock %}

adv_blog/advcbv/basic_app/templates/basic_app/school_form.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
  <h1>
    {% if not form.instance.pk %}
      Create School
    {% else %}
      Update School
    {% endif %}
  </h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="submit">
  </form>
{% endblock %}

adv_blog/advcbv/basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
  <h1>Welcome to the list off all the Schools</h1>
  <ol>
    {% for school in school %}
    <h2><li><a href="{% url 'basic_app:detail' pk=school.pk %}">{{ school.name }}</a></li></h2>
    {% endfor %}
  </ol>
{% endblock %}